# Generated by Django 6.0 on 2025-12-15 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='files.filecategory', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '文件分类',
                'verbose_name_plural': '文件分类',
                'db_table': 'file_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='文件名')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/', verbose_name='文件')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('file_type', models.CharField(blank=True, max_length=100, verbose_name='文件类型')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME类型')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='标签(逗号分隔)')),
                ('status', models.CharField(choices=[('active', '正常'), ('archived', '已归档'), ('deleted', '已删除')], default='active', max_length=20, verbose_name='状态')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='files.filecategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
                'db_table': 'files',
                'ordering': ['-created_at'],
            },
        ),
    ]
