# Generated by Django 6.0 on 2025-12-16 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('system', '0004_menu_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='system.department', verbose_name='所属部门'),
        ),
    ]
