# Generated by Django 6.0.3 on 2026-04-03 02:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_department'),
        ('system', '0005_loginlog_sys_login_l_created_a9a1a1_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['status', 'file_type'], name='files_status_153599_idx'),
        ),
    ]
