# Generated by Django 6.0 on 2025-12-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='登录时间'),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='username',
            field=models.CharField(db_index=True, max_length=150, verbose_name='登录用户名'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='module',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='模块'),
        ),
    ]
