# Generated by Django 6.0 on 2025-12-16 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('path', models.CharField(blank=True, max_length=200, null=True, verbose_name='路由路径')),
                ('component', models.CharField(blank=True, max_length=200, null=True, verbose_name='组件路径')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='图标')),
                ('menu_type', models.CharField(choices=[('directory', '目录'), ('menu', '菜单'), ('button', '按钮')], default='menu', max_length=20, verbose_name='菜单类型')),
                ('permission', models.CharField(blank=True, max_length=100, null=True, verbose_name='权限标识')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('visible', models.BooleanField(default=True, verbose_name='是否显示')),
                ('cache', models.BooleanField(default=True, verbose_name='是否缓存')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='system.menu', verbose_name='上级菜单')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单管理',
                'db_table': 'sys_menu',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20, verbose_name='角色')),
                ('data_scope', models.CharField(choices=[('all', '全部数据'), ('dept', '本部门数据'), ('dept_child', '本部门及以下数据'), ('self', '仅本人数据'), ('custom', '自定义数据')], default='self', max_length=20, verbose_name='数据权限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('departments', models.ManyToManyField(blank=True, to='system.department', verbose_name='自定义部门')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='system.menu', verbose_name='菜单')),
            ],
            options={
                'verbose_name': '角色权限',
                'verbose_name_plural': '角色权限管理',
                'db_table': 'sys_role_permission',
                'unique_together': {('role', 'menu')},
            },
        ),
    ]
