# Generated by Django 6.0.3 on 2026-04-03 02:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_menu_rolepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['created_at', 'status'], name='sys_login_l_created_a9a1a1_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['created_at', 'module'], name='sys_operati_created_14e545_idx'),
        ),
    ]
