# Generated by Django 6.0 on 2025-12-16 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0002_file_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='配置名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('source_sheet', models.CharField(blank=True, max_length=100, verbose_name='源文件Sheet')),
                ('reference_sheet', models.CharField(blank=True, max_length=100, verbose_name='对照文件Sheet')),
                ('target_sheet', models.CharField(blank=True, max_length=100, verbose_name='目标文件Sheet')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '已激活'), ('disabled', '已禁用')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mappings', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('reference_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_mappings', to='files.file', verbose_name='对照文件')),
                ('source_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_mappings', to='files.file', verbose_name='源文件')),
                ('target_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_mappings', to='files.file', verbose_name='目标文件模板')),
            ],
            options={
                'verbose_name': '数据映射配置',
                'verbose_name_plural': '数据映射配置',
                'db_table': 'data_mappings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MappingField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_field', models.CharField(max_length=200, verbose_name='源字段')),
                ('source_field_index', models.IntegerField(default=0, verbose_name='源字段索引')),
                ('reference_field', models.CharField(blank=True, max_length=200, verbose_name='对照字段')),
                ('reference_field_index', models.IntegerField(default=0, verbose_name='对照字段索引')),
                ('target_field', models.CharField(max_length=200, verbose_name='目标字段')),
                ('target_field_index', models.IntegerField(default=0, verbose_name='目标字段索引')),
                ('field_type', models.CharField(choices=[('source_to_target', '源→目标'), ('source_to_ref', '源→对照'), ('ref_to_target', '对照→目标'), ('source_ref_target', '源→对照→目标')], default='source_to_target', max_length=30, verbose_name='映射类型')),
                ('transform_rule', models.JSONField(blank=True, null=True, verbose_name='转换规则')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='processing.datamapping', verbose_name='所属配置')),
            ],
            options={
                'verbose_name': '字段映射',
                'verbose_name_plural': '字段映射',
                'db_table': 'mapping_fields',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('total_rows', models.IntegerField(default=0, verbose_name='总行数')),
                ('processed_rows', models.IntegerField(default=0, verbose_name='已处理行数')),
                ('success_rows', models.IntegerField(default=0, verbose_name='成功行数')),
                ('error_rows', models.IntegerField(default=0, verbose_name='错误行数')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='processing_results/%Y/%m/', verbose_name='结果文件')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='processing.datamapping', verbose_name='映射配置')),
            ],
            options={
                'verbose_name': '处理任务',
                'verbose_name_plural': '处理任务',
                'db_table': 'processing_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
