# Generated by Django 6.0 on 2025-12-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingfield',
            name='compute_expression',
            field=models.CharField(blank=True, max_length=500, verbose_name='计算表达式'),
        ),
        migrations.AddField(
            model_name='mappingfield',
            name='default_value',
            field=models.CharField(blank=True, max_length=500, verbose_name='默认值'),
        ),
        migrations.AddField(
            model_name='mappingfield',
            name='reference_code_column',
            field=models.CharField(blank=True, max_length=200, verbose_name='对照表编码列'),
        ),
        migrations.AddField(
            model_name='mappingfield',
            name='reference_name_column',
            field=models.CharField(blank=True, max_length=200, verbose_name='对照表名称列'),
        ),
        migrations.AddField(
            model_name='mappingfield',
            name='reference_sheet',
            field=models.CharField(blank=True, max_length=100, verbose_name='对照表Sheet'),
        ),
        migrations.AlterField(
            model_name='mappingfield',
            name='field_type',
            field=models.CharField(choices=[('direct', '直接映射'), ('lookup', '对照表转换'), ('computed', '计算字段'), ('default', '默认值'), ('source_to_target', '源→目标'), ('source_to_ref', '源→对照'), ('ref_to_target', '对照→目标'), ('source_ref_target', '源→对照→目标')], default='direct', max_length=30, verbose_name='映射类型'),
        ),
        migrations.AlterField(
            model_name='mappingfield',
            name='reference_field_index',
            field=models.IntegerField(default=-1, verbose_name='对照字段索引'),
        ),
        migrations.AlterField(
            model_name='mappingfield',
            name='source_field',
            field=models.CharField(blank=True, max_length=200, verbose_name='源字段'),
        ),
        migrations.AlterField(
            model_name='mappingfield',
            name='source_field_index',
            field=models.IntegerField(default=-1, verbose_name='源字段索引'),
        ),
        migrations.AlterField(
            model_name='mappingfield',
            name='target_field_index',
            field=models.IntegerField(default=-1, verbose_name='目标字段索引'),
        ),
    ]
