# Generated by Django 6.0.3 on 2026-04-03 02:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_files_status_153599_idx'),
        ('processing', '0002_mappingfield_compute_expression_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='datamapping',
            index=models.Index(fields=['status', 'created_by'], name='data_mappin_status_2cc3ac_idx'),
        ),
        migrations.AddIndex(
            model_name='processingtask',
            index=models.Index(fields=['status', 'created_by'], name='processing__status_da06d2_idx'),
        ),
        migrations.AddIndex(
            model_name='processingtask',
            index=models.Index(fields=['created_at'], name='processing__created_1eda4d_idx'),
        ),
    ]
