# Generated by Django 6.0.3 on 2026-04-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_datamapping_data_mappin_status_2cc3ac_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingtask',
            name='celery_task_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Celery任务ID'),
        ),
    ]
